import { ArrowRight, CalendarClock, ChevronRight, CircleAlert, PackageCheck, RefreshCw, ShieldAlert, TrendingUp } from 'lucide-react';
import { Link } from 'wouter';
import { useMemo } from 'react';
import { getGetDashboardSummaryQueryKey, getHealthCheckQueryKey, getListDrugsQueryKey, useGetDashboardSummary, useHealthCheck, useListDrugs } from '@workspace/api-client-react';
import { StatusBadge } from '@/components/status-badge';

const dateLabel = (date: string) => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date));

function Metric({ label, value, note, tone, icon: Icon }: { label: string; value?: number; note: string; tone: 'safe' | 'watch' | 'danger' | 'neutral'; icon: typeof PackageCheck }) {
  return <div className={`metric-card metric-${tone}`}><div className="flex items-start justify-between"><div className="metric-icon"><Icon size={18} /></div><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{label}</span></div><div className="mt-7 flex items-end justify-between"><span className="font-mono text-[38px] leading-none tracking-[-0.08em]">{value === undefined ? <span className="inline-block h-9 w-14 animate-pulse rounded bg-muted" /> : value}</span><span className="text-right text-[11px] text-muted-foreground">{note}</span></div></div>;
}

export function DashboardPage() {
  const summary = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey() } });
  const drugs = useListDrugs(undefined, { query: { queryKey: getListDrugsQueryKey() } });
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey() } });
  const recent = useMemo(() => [...(drugs.data ?? [])].sort((a, b) => +new Date(b.updatedAt) - +new Date(a.updatedAt)).slice(0, 5), [drugs.data]);
  const isLoading = summary.isLoading || drugs.isLoading;
  const hasError = summary.isError || drugs.isError;
  const lastSync = summary.data?.updatedAt ? dateLabel(summary.data.updatedAt) : 'awaiting sync';
  return <div className="space-y-9 page-enter">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="eyebrow"><span className="live-dot" /> Morning inventory brief</div><h1 className="page-title">Expiry health, <em>at a glance.</em></h1><p className="page-subtitle">Keep the shelf honest before the next sale starts.</p></div><div className="flex items-center gap-3"><div className={`connection-chip ${health.data?.status === 'ok' ? 'is-online' : ''}`} data-testid="status-api-connection"><span className="h-1.5 w-1.5 rounded-full bg-current" /> API {health.isLoading ? 'checking' : health.data?.status === 'ok' ? 'connected' : 'standby'}</div><Link href="/drugs" className="button-primary" data-testid="link-manage-records">Manage records <ArrowRight size={16} /></Link></div></section>
    {hasError && <div className="state-error" role="alert" data-testid="status-dashboard-error"><ShieldAlert size={20} /><div><strong>We could not read the expiry ledger.</strong><p>Check the API connection, then try again.</p></div><button type="button" onClick={() => { summary.refetch(); drugs.refetch(); health.refetch(); }} className="button-quiet ml-auto" data-testid="button-retry-dashboard"><RefreshCw size={15} /> Retry</button></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Total tracked" value={summary.data?.total} note="all records" tone="neutral" icon={TrendingUp} /><Metric label="Within range" value={summary.data?.good} note="30+ days out" tone="safe" icon={PackageCheck} /><Metric label="Expiring soon" value={summary.data?.expiring} note="next 30 days" tone="watch" icon={CalendarClock} /><Metric label="Expired" value={summary.data?.expired} note="action required" tone="danger" icon={CircleAlert} />
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]">
      <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-5 md:px-6"><div><p className="eyebrow">Recent movement</p><h2 className="section-title">Recently updated</h2></div><Link href="/drugs" className="icon-link" data-testid="link-view-all-drugs">View all <ArrowRight size={14} /></Link></div>
        {isLoading ? <div className="space-y-4 p-6">{[1, 2, 3].map((n) => <div key={n} className="skeleton-row" />)}</div> : recent.length === 0 ? <div className="empty-state"><div className="empty-mark"><PackageCheck size={22} /></div><h3>No records yet</h3><p>Once you add medicines, your latest changes will appear here.</p><Link href="/drugs" className="button-primary" data-testid="link-empty-add-drug">Add first record</Link></div> : <div className="divide-y divide-border">{recent.map((drug) => <Link href="/drugs" key={drug.id} className="record-row group" data-testid={`row-recent-drug-${drug.id}`}><div className="min-w-0"><div className="flex items-center gap-3"><span className="truncate text-sm font-bold">{drug.name}</span><StatusBadge status={drug.status} /></div><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground">Updated {dateLabel(drug.updatedAt)} {drug.batchNumber ? `· batch ${drug.batchNumber}` : ''}</p></div><div className="flex items-center gap-3 text-right"><span className={`font-mono text-xs ${drug.daysUntilExpiry < 0 ? 'text-destructive' : drug.daysUntilExpiry < 30 ? 'text-foreground' : 'text-muted-foreground'}`}>{drug.daysUntilExpiry < 0 ? `${Math.abs(drug.daysUntilExpiry)}d overdue` : `${drug.daysUntilExpiry}d left`}</span><ChevronRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-1" /></div></Link>)}</div>}
      </div>
      <div className="panel flex flex-col justify-between overflow-hidden"><div className="border-b border-border p-6"><p className="eyebrow">Last ledger sync</p><h2 className="mt-3 font-mono text-2xl tracking-[-0.06em]">{lastSync}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Dashboard totals reflect the latest available medicine record.</p></div><div className="space-y-4 p-6"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-muted-foreground"><span className="h-2 w-2 rounded-full bg-primary" /> Safe stock</span><span className="font-mono">{summary.data?.good ?? '—'}</span></div><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-muted-foreground"><span className="h-2 w-2 rounded-full bg-accent" /> Watch list</span><span className="font-mono">{summary.data?.expiring ?? '—'}</span></div><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-muted-foreground"><span className="h-2 w-2 rounded-full bg-destructive" /> Remove / review</span><span className="font-mono">{summary.data?.expired ?? '—'}</span></div><Link href="/extension" className="mt-3 flex items-center justify-between rounded-xl bg-secondary px-4 py-3 text-xs font-bold transition-colors hover:bg-accent" data-testid="link-dashboard-extension">Configure LavaBMS bridge <ChevronRight size={15} /></Link></div></div>
    </section>
  </div>;
}