import { Check, Clipboard, Code2, ExternalLink, FileKey2, PlugZap, RefreshCw, ShieldCheck, TerminalSquare } from 'lucide-react';
import { useState } from 'react';
import { getHealthCheckQueryKey, useHealthCheck } from '@workspace/api-client-react';

const apiBaseUrl = typeof window !== 'undefined' ? `${window.location.origin}/api` : '/api';

export function ExtensionPage() {
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey() } });
  const [copied, setCopied] = useState('');
  const copy = (value: string, key: string) => { navigator.clipboard?.writeText(value); setCopied(key); window.setTimeout(() => setCopied(''), 1800); };
  return <div className="space-y-8 page-enter">
    <section><div className="eyebrow"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Integration</div><h1 className="page-title">The bridge to <em>checkout.</em></h1><p className="page-subtitle max-w-[620px]">Install the LavaBMS browser extension once. From then on, matching medicine names show the right expiry signal while your team is serving a customer.</p></section>
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="panel overflow-hidden"><div className="border-b border-border p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><PlugZap size={23} /></div><h2 className="mt-5 text-xl font-extrabold">LavaBMS extension setup</h2><p className="mt-2 max-w-[520px] text-sm leading-6 text-muted-foreground">The extension reads the item currently open in LavaBMS and checks it against this console. Checkout stays uninterrupted; the warning lives beside the item.</p></div><span className="rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.12em] text-primary">3 steps</span></div></div>
        <div className="space-y-1 p-6 md:p-8">{[{ n: '01', icon: FileKey2, title: 'Load the extension', text: 'Open your browser’s extension manager and choose Developer mode → Load unpacked.' }, { n: '02', icon: TerminalSquare, title: 'Point it at this console', text: 'Use the connection address below as the extension API origin. Keep it on the same network as LavaBMS.' }, { n: '03', icon: ShieldCheck, title: 'Run a live match', text: 'Open a medicine in LavaBMS. A status badge will appear when the name matches a tracked record.' }].map(({ n, icon: Icon, title, text }) => <div className="setup-step" key={n}><div className="step-number">{n}</div><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><Icon size={17} /></div><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div></div>)}</div>
      </div>
       <div className="space-y-5"><div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><p className="eyebrow">Connection details</p><h2 className="section-title">Ready when you are</h2></div><div className={`connection-chip ${health.data?.status === 'ok' ? 'is-online' : ''}`} data-testid="status-extension-health"><span className="h-1.5 w-1.5 rounded-full bg-current" />{health.isLoading ? 'Checking' : health.data?.status === 'ok' ? 'Online' : 'Offline'}</div></div><div className="space-y-4 p-6"><div><span className="field-label">Extension API URL</span><div className="copy-field"><code data-testid="text-api-origin">{apiBaseUrl}</code><button type="button" onClick={() => copy(apiBaseUrl, 'origin')} title="Copy extension API URL" data-testid="button-copy-api-origin">{copied === 'origin' ? <Check size={15} /> : <Clipboard size={15} />}</button></div></div><div><span className="field-label">Health endpoint</span><div className="copy-field"><code data-testid="text-health-endpoint">/api/healthz</code><button type="button" onClick={() => copy(`${apiBaseUrl}/healthz`, 'health')} title="Copy health endpoint" data-testid="button-copy-health-endpoint">{copied === 'health' ? <Check size={15} /> : <Clipboard size={15} />}</button></div></div><div className="flex items-center gap-2 pt-2 text-xs text-muted-foreground"><span className={`h-2 w-2 rounded-full ${health.data?.status === 'ok' ? 'bg-primary' : 'bg-accent'}`} />Last check {health.isFetched ? 'just now' : 'pending'}<button type="button" onClick={() => health.refetch()} className="ml-auto rounded p-1 hover:bg-secondary" title="Refresh health" data-testid="button-refresh-health"><RefreshCw size={14} className={health.isFetching ? 'animate-spin' : ''} /></button></div></div></div>
         <a href="/lavabms-drug-expiry-extension.zip" download className="flex items-center justify-between rounded-2xl border border-primary/20 bg-primary/10 p-5 text-sm font-bold text-primary transition-colors hover:bg-primary/15" data-testid="link-download-extension"><span>Download the extension package</span><ExternalLink size={16} /></a>
        <div className="rounded-2xl border border-primary/20 bg-primary/10 p-6"><div className="flex items-start gap-3"><Code2 size={18} className="mt-0.5 shrink-0 text-primary" /><div><h3 className="text-sm font-bold">What the extension can see</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Only the current product name and the expiry result are exchanged. Record editing stays here, in the console.</p><a href="https://lavabms.com" target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-primary" data-testid="link-lavabms-help">Open LavaBMS help <ExternalLink size={13} /></a></div></div></div></div>
    </section>
  </div>;
}